### ISSUE TITLE
Copy to clipboard

### ISSUE THREAD

**Issue by ShabbyX** [KhronosGroup/SPIRV-Visualizer#26]
With the visualizer able to decode a list of hex values into SPIR-V, it would be great if said SPIR-V could be copied out of the visualizer (so for example one could then copy it to a file and run it through spirv-cross).

A "Copy to Clipboard" button should do the trick! A "Save to File" button would also serve this purpose, but the former gives the user more options.

**Comment by spencer-lunarg** [comment]
I might start with a "Save to File" as it would be easier since the data is in a binary format already

the copy-to-clipboard might be a tad harder as the assembler logic brings the text to a binary format that is then re-parsed, but should be able to slight modify the current dissemble logic to be loaded by a `spirv-as`/`spirv-cross` binary

**Comment by spencer-lunarg** [comment]
so finally had time to try this, was not the worst and have something that I assume is 98% going to work

there are a few edge case instructions I display differently then the standard `spirv-as` does, but should be good... of course let me know if you try to use it and find issues!
